# prompts_lib/cc_reverse/v2_1_81/lib.py

from __future__ import annotations

import platform
from pathlib import Path

from ccserver.prompts_lib.base import PromptLib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ccserver.session import Session
_SLOTS_DIR = Path(__file__).parent


def _load(name: str) -> str:
    """读取 v2.1.81 目录下的 .md slot 文件。"""
    return (_SLOTS_DIR / f"{name}.md").read_text(encoding="utf-8")


def _build_env_string(project_root: Path, model: str) -> str:
    return (
        f" - Primary working directory: {project_root}\n"
        f"  - Is a git repository: true\n"
        f" - Platform: {platform.system()}\n"
        f" - Shell: zsh\n"
        f" - OS Version: {platform.system()} {platform.release()}\n"
        f" - You are powered by the model named {model}. The exact model ID is {model}.\n"
        f" -"
    )


class CcReverseV2181(PromptLib):
    """
    cc_reverse:v2.1.81 的提示词拼接实现。

    模仿 Claude Code 的 system prompt 结构：
      1. billing header
      2. system-identity（角色定义）
      3. system-workflow（行为规范，含环境信息和语言设置）

    user message 注入模式：
      把 reminders（CLAUDE.md、当前日期、技能列表等）作为
      <system-reminder> 块追加到 content 列表里，模仿 Claude Code 行为。
    """

    # lib_id 中的版本号，如 "cc_reverse:v2.1.81" → "2.1.81"
    _VERSION = "2.1.81"

    def build_system(self, session: Session, model: str, language: str, cch: str = "", injected_system: list | None = None, append_system:bool=True, is_spawn: bool = False) -> list:
        identity = _load("system-identity")
        
        billing = f"x-anthropic-billing-header: cc_version={self._VERSION}; cc_entrypoint=cli; cch={cch};"
        result = [
            {"type": "text", "text": billing},
            {"type": "text", "text": identity},
        ]
        if not is_spawn:
            workflow = (
                _load("system-workflow")
                .replace("✿ENV_STRING✿", _build_env_string(session.project_root, model))
                .replace("✿LANGUAGE✿", language)
            )
            if injected_system:
                if append_system:
                    workflow += "\n"+injected_system
                else:
                    workflow = injected_system
            result.append({"type": "text", "text": workflow})

        else:

            # injected_system 追加到末尾
            if injected_system:
                result.extend({"type": "text", "text": injected_system})
        return result

    def build_skill_catalog(self, skills: list) -> str:
        """
        生成替换 system-reminder-skill-inject.md 中 ✿SKILLS✿ 占位符的内容。
        slot 文件本身已包含说明文字，这里只返回条目列表。
        """
        if not skills:
            return ""
        entries = "\n".join(
            f"- {s['name']}: {s['description']}"
            for s in skills
        )
        return entries

    def build_command_message(self, cmd_info: dict, session: Session, history: list) -> list:
        """
        按 Claude Code 格式包装 command 消息：
          1. CLAUDE.md reminder
          2. local-command-caveat
          3. command 结构块（name/message/args）
          4. stdout（如果有）
          5. command body + ARGUMENTS
        """
        parts = []
        name = cmd_info.get("name", "")
        args = cmd_info.get("args", "")
        stdout = cmd_info.get("stdout", "")
        body = cmd_info.get("body", "")

        # 1. CLAUDE.md reminder
        claude_md_reminder = self._build_claude_md_reminder(session)
        if claude_md_reminder:
            parts.append({"type": "text", "text": f"<system-reminder>\n{claude_md_reminder}\n</system-reminder>"})

        # 2. local-command-caveat
        caveat = (
            "<local-command-caveat>Caveat: The messages below were generated by the user "
            "while running local commands. DO NOT respond to these messages or otherwise "
            "consider them in your response unless the user explicitly asks you to.</local-command-caveat>"
        )
        parts.append({"type": "text", "text": caveat})

        # 3. command 结构块
        cmd_block = (
            f"<command-name>/{name}</command-name>\n"
            f"<command-message>{name}</command-message>\n"
            f"<command-args>{args}</command-args>"
        )
        parts.append({"type": "text", "text": cmd_block})

        # 4. stdout（如果有）
        if stdout:
            parts.append({"type": "text", "text": f"<local-command-stdout>{stdout}</local-command-stdout>"})

        # 5. command body + ARGUMENTS
        if body:
            suffix = f"\n\nARGUMENTS: {args}" if args else ""
            parts.append({"type": "text", "text": f"{body}{suffix}"})

        return parts

    def _build_claude_md_reminder(self, session: Session) -> str:
        """构建 CLAUDE.md + currentDate 的 reminder 文本，找不到文件时返回空字符串。"""
        claude_md_path = session.project_root / "CLAUDE.md"
        if not claude_md_path.exists():
            return ""

        from datetime import date
        p0 = _load("system-reminder-claude-md-inject-p0")
        p1 = (
            _load("system-reminder-claude-md-inject-p1")
            .replace("✿PATH_OF_PROJECT_CLAUDE_MD✿", str(claude_md_path))
            .replace("✿CALUDE_MD✿", claude_md_path.read_text(encoding="utf-8"))
        )
        p2 = (
            _load("system-reminder-claude-md-inject-p2")
            .replace("✿CURRENT_DATE✿", date.today().isoformat())
        )
        return f"{p0}\n{p1}\n{p2}"

    def build_user_message(self, text: str, session: Session, context: dict) -> list:
        """
        将 text 和 reminders 打包为 content block 列表，模仿 Claude Code 行为。

        context 字段：
          is_first        — 是否第一条 user 消息，True 时注入 skill/CLAUDE.md/日期
          hook_context    — UserPromptSubmit hook 附加内容（可选字符串）
          skills_override — None = 使用 session 全局 skills；list[str] = 只用列出的 skill 名称
        """
        parts = []

        if not context.get("is_first"):
            parts.append({"type": "text", "text": text})
            return parts

        # ── 第一条消息：注入三组 system-reminder ──────────────────────────

        # 1. skill inject（技能目录）
        skills_override = context.get("skills_override")  # None | list[str]

        if skills_override is None:
            # 根 agent：使用 session 全局 skills + commands
            local_skills = session.skills.list_skills() if session.skills else []
            local_commands = session.commands.list_commands() if session.commands else []
            all_entries = local_skills + local_commands
        elif len(skills_override) == 0:
            # subagent 未指定 skills：不注入任何 skill catalog
            all_entries = []
        else:
            # subagent 指定了 skills：只注入列出的 skill 名称
            allowed = set(skills_override)
            all_skills = session.skills.list_skills() if session.skills else []
            all_entries = [s for s in all_skills if s["name"] in allowed]

        skill_catalog = self.build_skill_catalog(all_entries)
        if skill_catalog:
            skill_template = _load("system-reminder-skill-inject")
            skill_text = skill_template.replace("✿SKILLS✿", "\n" + skill_catalog)
            parts.append({"type": "text", "text": f"<system-reminder>\n{skill_text}\n</system-reminder>"})

        # 2. UserPromptSubmit hook 附加上下文（如果有）
        hook_context = context.get("hook_context", "")
        if hook_context:
            parts.append({
                "type": "text",
                "text": f"<system-reminder>\n{hook_context}\n</system-reminder>",
            })

        # 3. CLAUDE.md inject + currentDate
        claude_md_reminder = self._build_claude_md_reminder(session)
        if claude_md_reminder:
            parts.append({"type": "text", "text": f"<system-reminder>\n{claude_md_reminder}\n</system-reminder>"})

        parts.append({"type": "text", "text": text})
        return parts
