from .base import BuiltinTools, ToolParam, ToolResult

# Sentinel checked by Agent._handle_tools() to detect subagent spawn requests.
AGENT_SIGNAL = "__AGENT__"

_BASE_DESCRIPTION = """\
Launch a new agent to handle complex, multi-step tasks autonomously.

The Agent tool launches specialized agents (subprocesses) that autonomously handle \
complex tasks. Each agent type has specific capabilities and tools available to it.

{agent_catalog}

When using the Agent tool, specify a subagent_type parameter to select which agent \
type to use. If omitted, a generic subagent that inherits all parent tools is used."""


class BTAgent(BuiltinTools):
    """
    Tool for spawning a subagent to handle a complex or delegated task.

    This tool is intercepted by Agent._handle_tools() — the run() method is never
    actually called. The tool exists so LLM can see its schema and call it properly.
    """

    name = "Agent"

    params = {
        "prompt": ToolParam(
            type="string",
            description="The task for the agent to perform",
        ),
        "description": ToolParam(
            type="string",
            description="A short (3-5 word) description of the task",
        ),
        "subagent_type": ToolParam(
            type="string",
            description="The type of specialized agent to use for this task",
            required=False,
        ),
        "model": ToolParam(
            type="string",
            description=(
                "Optional model override for this agent. Takes precedence over the agent "
                "definition's model frontmatter. If omitted, uses the agent definition's "
                "model, or inherits from the parent."
            ),
            required=False,
        ),
        "run_in_background": ToolParam(
            type="boolean",
            description="Set to true to run this agent in the background. You will be notified when it completes.",
            required=False,
        ),
        "isolation": ToolParam(
            type="string",
            description='Isolation mode. "worktree" creates a temporary git worktree so the agent works on an isolated copy of the repo.',
            required=False,
        ),
        "team_name": ToolParam(
            type="string",
            description='Optional team name. If provided alongside "name", spawns the agent as a teammate in the specified team (requires userAgentTeam=true).',
            required=False,
        ),
        "name": ToolParam(
            type="string",
            description='Optional teammate name within a team (e.g. "researcher"). Must be used together with "team_name".',
            required=False,
        ),
    }

    def __init__(self, agent_catalog: str = ""):
        """
        agent_catalog: generated by AgentLoader.build_catalog().
        Empty string means no predefined agents, only generic subagents are supported.
        """
        if agent_catalog:
            catalog_section = f"Available agent types and the tools they have access to:\n{agent_catalog}"
        else:
            catalog_section = "No predefined agent types available. Only generic subagents can be spawned."
        self.description = _BASE_DESCRIPTION.format(agent_catalog=catalog_section)

    async def run(
        self,
        prompt: str,
        description: str = "",
        subagent_type: str = "",
        model: str = "",
        run_in_background: bool = False,
        isolation: str = "",
    ) -> ToolResult:
        # This method is never actually called.
        # Agent._handle_tools() intercepts calls to "Agent" directly.
        return ToolResult.ok("")
