"""
ccserver/messages/tool_call.py

Codec decode 输出的工具调用扁平结构，直接供 Provider 和 LLMCaller 使用。
纯数据结构，无序列化方法，无外部依赖。
provider_data 是运行时内存字段，不序列化、不持久化。

Flat tool call structure output by Codec.decode, used directly by Provider and LLMCaller.
Pure data structure — no serialization, no external dependencies.
provider_data is a runtime-only field: not serialized, not persisted.
"""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class UnifiedToolCall:
    """
    Codec decode 输出的工具调用，扁平结构，直接供 Provider 和 LLMCaller 使用。
    Flat tool call structure decoded by Codec, for direct use by Provider and LLMCaller.

    Fields:
        id:            工具调用 ID，由 provider 生成 / Tool call ID generated by provider
        name:          工具名称 / Tool name
        input:         已解析的参数字典（JSON -> dict）/ Parsed arguments dict (JSON -> dict)
        provider_data: 运行时附加数据，不序列化。
                       可包含 call_id / response_item_id / thought_signature 等 provider 私有字段。
                       / Runtime-only metadata, not serialized.
                         May include provider-private fields like call_id, response_item_id, thought_signature.
    """
    id: str
    name: str
    input: dict                               # 已解析的 JSON dict / Parsed JSON dict
    provider_data: Optional[dict] = None      # 运行时内存，不序列化 / Runtime only, not serialized
